workers:
    - name: 'top-tagger'
      type: 'docker'
workflow:
    - step: 'pre-processor'
      worker: 'top-tagger'
    - step: 'top-tagger'
      worker: 'top-tagger'
    - step: 'model-evaluater'
      worker: 'top-tagger'
    - step: 'update-results'
      worker: 'top-tagger'
